pipeline {
    agent any

    tools {
        nodejs "node20"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Sanju2254/vpro-santhosh-appln.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build Vite App') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t vite-react-app .'
            }
        }

        stage('Remove Old Container') {
            steps {
                sh 'docker rm -f vite-react-container || true'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 3000:3000 --name vite-react-container vite-react-app'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs!'
        }
    }
}